### ISSUE TITLE
ActivityLog DevTools panel

### ISSUE THREAD

**Issue by rpl** [mozilla/extension-activity-monitor#22]
As being discussed in out last meeting, to make it easier to look to logs related to a particular tab we could register a devtools panel and load the activity log page into it.

When the activitylog page is loaded as a devtools panel the logs should be filtered automatically by tab id based on the value of the `browser.devtools.inspectedWindow.tabId`.

**Comment by rpl** [comment]
As we discussed in the weekly meeting:

The activitylog page itself would not be using the devtools API directly, it will just look to the search params and if there is a search param like `filterTabId=...` then it would use that to filter the tab Id (and also make it visible in the page that the logs are being automatically filtered by tabId.

To learn more about the devtools API and how to integrate an extension page into the developer tools you may take a look to the following doc page on MDN: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools

Some other details that may be useful to you:
 
- the extension manifest should include a [`devtools_page` manifest property](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/devtools_page) and it should be set to an html file packaged in the extension
- the devtools page is invisible (similarly to a background page), and it is created automatically when a developer toolbox is opened on a Firefox tab (there will be 1 devtools page instance per developer toolbox, and no more than 1 developer toolbox per tab)
- the devtools page is one of the extension pages that can use the devtools API, and our devtools page should use it to:
  - retrieve the `tabId` for the tab where the developer toolbox has been opened using [`browser.devtools.inspectedWindow.tabId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow/tabId) (that `tabId` doesn't change, it will stay the same even if the page is navigated, every devtools_page instance is related to a different developer toolbox, each developer toolbox is related to a different tab and so the tabId will be different only in those cases)
  - the devtools page will use that `tabId` to compute the search params to add to the url of the activitylog page registered by the extension a devtools panel for the current developer toolbox
  - then it will use the computed activitylog page url to register the devtools panel on the current developer toolbox using the [`browser.devtools.panels.create` API method](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create)

Once the panel is registered, a new tool will be available to the user, the actual activitylog page will be loaded lazily when the user selects the panel.

Let me know if you need any additional detail or if any of the detail above are not clear enough.

**Comment by atiqueahmedziad** [comment]
Thanks a lot @rpl for explaining. Let me rephase it to check if I have understand the explanation correctly. 
Here is what I am going to do - 
1. I will make a new panel named "Extension Activity Monitor"/ "EAM" in the developer toolbox. (See the screenshot below) 
2. I will retrieve the `tabId` (where the developer toolbox has been opened) with [`browser.devtools.inspectedWindow.tabId`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.inspectedWindow/tabId). 
3. I will generate the activitylog page url like - activitylog.html?filterTabId=`TabId`
4. When user clicks on the "Extension Activity Monitor" / "EAM" button from developer toolbox, the `activitylog.html?filterTabId=TabId` page will open inside devtool panel. (like in the below screenshot)

### Question:
1. I will be matching [`this tabId`](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas/activity_log.json#63) property from logs with `TabId` from `filterTabId=TabId` to filter the logs. Am I right?
2. Should I use "Extension Activity Monitor" OR "EAM" as name to create the panel in developer toolbox ?

<img width="1280" alt="Screenshot 2020-08-06 at 9 36 16 PM" src="https://user-images.githubusercontent.com/8364578/89552547-1b84ba80-d82e-11ea-9f1a-ae49a1ee9bde.png">

**Comment by rpl** [comment]
@atiqueahmedziad yep, it looks right, that's a summary of the plan. 

Follows answers to the two questions:

> ### Question:
> 
>     1. I will be matching [`this tabId`](https://searchfox.org/mozilla-central/source/toolkit/components/extensions/schemas/activity_log.json#63) property from logs with `TabId` from `filterTabId=TabId` to filter the logs. Am I right?

yes, that's the idea.

>     2. Should I use "Extension Activity Monitor" OR "EAM" as name to create the panel in developer toolbox ?

I think that the label should be "Extension Activity Monitor".

**Comment by wagnerand** [comment]
> > ```
> > 2. Should I use "Extension Activity Monitor" OR "EAM" as name to create the panel in developer toolbox ?
> > ```
> 
> I think that the label should be "Extension Activity Monitor".

Or just "Extension Activity". Other panel names follow a similar scheme, e.g. "Network", instead of "Network Monitor".
