### ISSUE TITLE
Restore filters on page load

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/extension-activity-monitor#24]
Currently, the filters are lost once we reload the activitylog page or if we accidentally close the activitylog page. But we want the filters to be applied (that we set previously) on activitylog page loads.

**Comment by wagnerand** [comment]
The filters should be stored in the URL (as GET parameters) applied on load. The URL should be updated when the filters change.

**Comment by Rob--W** [comment]
You can use the `history.replaceState` API to replace the URL - https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState
