### ISSUE TITLE
Buttons in extension popup should be rounded

### ISSUE THREAD

**Issue by himanshujaidka** [mozilla/extension-activity-monitor#34]
![Screenshot (30)](https://user-images.githubusercontent.com/58654018/89678966-be603600-d90d-11ea-8250-73ef80aa128f.png)
Buttons are not looking good, this should have rounded edges

**Comment by Rob--W** [comment]
In your screenshot, you can see that Firefox's buttons are rectangular. Why should the extension deviate from that?

**Comment by himanshujaidka** [comment]
please see my pr #36 you will get an idea :)

**Comment by rpl** [comment]
as @Rob--W pointed out in another comment, this project is an ongoing GSOC project (and @atiqueahmedziad in actively working on it), more focus on the css side may be reasonable in a later phase after the extension is complete enough from an architecture perspective.

For the above reason I marked this issue as wontfix and I'm going to close the related PR.

**Comment by himanshujaidka** [comment]
Ok boss :)
