### ISSUE TITLE
ViewTypes filter options should not contain undefined

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/extension-activity-monitor#42]
While working with PR #31, I noticed for `log.type` = `api_call` the `viewType` can be `undefined`. See the screenshot below.

Currently we are only [filtering with `log.type` = `content_script`](https://github.com/mozilla/extension-activity-monitor/blob/master/src/lib/ext-activitylog.js#L166) to exclude the `undefined` from being added as a `viewType` filter option. I think we should be filtering out with `log.viewType` = `undefined` instead of `log.type` = `content_script` as `viewType` can be `undefined` in both log.type = content_scirpt and log.type = api_call.

## Screenshot
<img width="1280" alt="Screenshot 2020-08-12 at 9 49 50 PM" src="https://user-images.githubusercontent.com/8364578/90040597-f7235500-dce9-11ea-8a4d-d574842644c7.png">

**Comment by Rob--W** [comment]
I recommend against removing the `undefined` checkbox without replacement, because that prevents users from filtering api_call logs that don't have a viewType. The label can probably be improved (to be a bit less cryptic than `undefined`), but this is not a high priority.

**Comment by Rob--W** [comment]
Let's make it "other".
