### ISSUE TITLE
need to press filter button again so that it will close 

### ISSUE THREAD

**Issue by himanshujaidka** [mozilla/extension-activity-monitor#59]
we need to click back the button so that the options list will get close, it should be automatically close when the user clicks on the anywhere on the page
![Screenshot (84)](https://user-images.githubusercontent.com/58654018/94536151-0e011500-0260-11eb-8d9e-f07b6749e6b4.png)
.

**Comment by atiqueahmedziad** [comment]
This has been implemented in the current version and the UI/UX has been improved. Would you mind trying the current version of Extension Activity Monitor?

**Comment by himanshujaidka** [comment]
okay, sorry I think that I have not merged the current version

**Comment by himanshujaidka** [comment]
sorry, I found that
